module.exports = {
  IGStalk: require("./igstalk"),
  KBBI: require("./kbbi"),
  Lirik: require("./lirik"),
  Cuaca: require("./cuaca"),
  IG: require("./ig"),
  FB: require("./fb"),
  IpLookup: require("./iplookup"),
  Tiktok: require("./tiktok"),
  Vokal: require("./vokal"),
  Headers: require("./headers"),
  Covid: require("./covid"),
  Simi: require("./simi"),
  Github: require("./github"),
  Shortlink: require("./shortlink"),
  WPUser: require("./wpuser"),
  Emoji: require("./emoji"),
  Joox: require("./joox"),
  ArtiNama: require("./artinama"),
  ArtiMimpi: require("./artimimpi")
};
